mv Panneau.java FPanel.java
mv PanneauActionSup.java FPanelActionSup.java
mv PanneauBouton.java FPanelBouton.java
mv PanneauCarte.java FPanelCarte.java
mv PanneauChamp.java FPanelChamp.java
mv PanneauChargement.java FPanelChargement.java
mv PanneauChoixPartie.java FPanelChoixPartie.java
mv PanneauDialogue.java FPanelDialogue.java
mv PanneauDialogueInf.java FPanelDialogueInf.java
mv PanneauEchap.java FPanelEchap.java
mv PanneauFinPartie.java FPanelFinPartie.java
mv PanneauGEtiquetteJoueur.java FPanelGEtiquetteJoueur.java
mv PanneauInfo.java FPanelInfo.java
mv PanneauInfoCreature.java FPanelInfoCreature.java
mv PanneauInfoText.java FPanelInfoText.java
mv PanneauJeu.java FPanelJeu.java
mv PanneauLanceurPartie.java FPanelLanceurPartie.java
mv PanneauMenu.java FPanelMenu.java
mv PanneauMiniMap.java FPanelMiniMap.java
mv PanneauMiniMapContainer.java FPanelMiniMapContainer.java
mv PanneauNouvellePartie.java FPanelNouvellePartie.java
mv PanneauPrincipal.java FPanelPrincipal.java
mv PanneauSup.java FPanelSup.java
mv PanneauTBoolean.java FPanelTBoolean.java
mv PanneauTInt.java FPanelTInt.java
mv PanneauTX.java FPanelTX.java
mv PanneauZoom.java FPanelZoom.java
