name: Update coverage value

on:
  push:
    branches:
    - "*"

jobs:
  updateValue:
    runs-on: ubuntu-latest
    steps:
    - name: Dynamic Badges
      uses: emibcn/badge-action@v1
      with:
        label: 'Test coverage'
        status: '53.4%'
        color: 'blue,555,daf'
        path: 'coverage.svg'
