
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Update language value

on:
  push:
    branches:
    - "*"

jobs:
  compile:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Dynamic Badges
      uses: Schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: <gist-ID>
        filename: fr.json
        label: French
        message: 98%
        color: gree
