name: Update language value

on:
  push:
    branches:
    - "*"

jobs:
  updateValue:
    runs-on: ubuntu-latest
    name: Udpate coverage value
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven
      run: mvn -ntp compile -c
    - name: Generate 3 language value
      id: dataCreation
      run: |
        # Generates a GitHub Workflow output named `status`
        VALUE=$(./run.sh -q trad fr)
        echo "##[set-output name=status;]${VALUE}"
        #echo "##[set-output name=status;]$(./run.sh -q trad fr)"
        #if: ${VALUE} < 40
        #  color="red"
        #if: ${VALUE} > 80
        #  color="green"
        #echo "##[set-output name=color;]$color"
        # Create the directory where badges will be saved, if needed
        mkdir -p "${BADGE_PATH%/*}"
        echo "##[set-output name=path;]${BADGE_PATH}"
      env:
        BADGE_PATH: .github/badges/fr.svg
        VALUE: 0
        COLOR: "yellow"

    # Use the output from the `coverage` step
    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v1
      id: badge
      with:
        label: 'Coverage'
        status: ${{ steps.dataCreation.outputs.status }}%
        color: "red"
        #${{ steps.dataCreation.outputs.color }}
        path: ${{ steps.dataCreation.outputs.path }}

    - name: Upload badge as artifact
      uses: actions/upload-artifact@v2
      with:
        name: badge
        path: ${{ steps.dataCreation.outputs.path }}
        if-no-files-found: error

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Commit badge
      env:
        BADGE: ${{ steps.dataCreation.outputs.path }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "${BADGE}"
        git commit -m "Add/Update badge"
    - name: Push badge commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
