name: Update language value

on:
  push:
    branches:
    - "*"

jobs:
  updateValue:
    runs-on: ubuntu-latest
    steps:
    - name: Dynamic Badges
      uses: Schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 94ab030542fa103562eff4f2f60b68a388960172
        filename: fr.json
        label: French
        message: 98%
        color: green
