# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven
      run: mvn compile -c
    - name: exe.sh
      run: ./exe.sh
    - name: version
      run: echo "::set-output name=version::$(cat version.md)"
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Formiko${{ steps.version.outputs.version }}
        tag_name: ${{ steps.version.outputs.version }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload Linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/Formiko${{ steps.version.outputs.version }}Linux.zip
        asset_name: Formiko${{ steps.version.outputs.version }}Linux.zip
        asset_content_type: application/zip
    - name: upload Windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/Formiko${{ steps.version.outputs.version }}Windows.zip
        asset_name: Formiko${{ steps.version.outputs.version }}Windows.zip
        asset_content_type: application/zip
    - name: upload Mac artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/Formiko${{ steps.version.outputs.version }}Mac.zip
        asset_name: Formiko${{ steps.version.outputs.version }}Mac.zip
        asset_content_type: application/zip
    - name: upload .jar artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/Formiko${{ steps.version.outputs.version }}.zip
        asset_name: Formiko${{ steps.version.outputs.version }}.zip
        asset_content_type: application/zip
